server:
  port: 8085

eureka:
  client:
    serviceUrl:
    #defaultZone: http://localhost:8090/eureka
      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:
  #hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
spring:
  cloud:
    gateway:

      discovery:
        locator:
          enable: true
      routes:
        - id: producto-db-service
          uri: lb://producto-db-service
          predicates:
            - Path=/categorias/**, /productos/**

        - id: ms-cliente-service
          uri: lb://ms-cliente-service
          predicates:
            - Path=/clientes/**

        - id: pedido-db-service
          uri: lb://pedido-db-service
          predicates:
            - Path=/pedido/**




